name: "Publish Package"

# Trigger when a new release is created
on:
  release:
    types: [created]

jobs:
  package:
    name: "Package & Push to GitHub Packages"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup - Checkout"
        uses: actions/checkout@v3

      - name: "Check for .nvmrc"
        run: |
          if [[ ! -f .nvmrc ]]; then
            echo "14" > .nvmrc
          fi

      - name: "Setup - Use Node.js (from .nvmrc)"
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@digital-uk'
          always-auth: true

      # Skip post-install scripts here, as a malicious
      # script could steal NODE_AUTH_TOKEN.
      - name: "Install dependencies"
        id: install_deps
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_GITHUB_ACTIONS_TOKEN }}

      # `npm rebuild` will run all those post-install scripts for us.
      - name: "Setup dependencies"
        id: setup_deps
        run: npm rebuild && npm run prepare --if-present

      - name: "Publish"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
